### ISSUE TITLE
Searching for a non-excisting icon causes a white area in dark mode

### ISSUE THREAD

**Issue by Bartvdgriendt** [tijme/raivo#8] opened 2019-08-15 09:51 UTC
When searching for a non-excisting icon causes a white area in dark mode, see GIF below:

![GIF](https://media.giphy.com/media/KFOtFPr7LQxXXv8GCx/source.gif)

 - Device: iPhone XS
 - OS: 13.0
 - Version 1.0.2 (13)

**Comment by tijme** [comment] 2019-08-16 06:46
Thanks for the report. This is something that I probably forgot while making the app Dark Mode compatible. This will be fixed in one of the upcoming releases.

Please note that Apple doesn't allow me to push Xcode11 builds to the App Store at the moment. This prevents me from publishing the Dark Mode feature to production at the moment.

**Comment by tijme** [comment] 2019-08-17 09:56
The issue is fixed with commit d899fa7. As stated before, please note that Apple doesn't allow me to push Xcode11 builds to the App Store at the moment. This prevents me from publishing the Dark Mode feature to production at the moment.

**Closed by tijme** 2019-08-17 09:56 UTC
Labels: Bug
